clone:
  path: github.com/drone/drone-exec

build:
  image: golang:1.5
  environment:
    - GOPATH=/drone
    - GO15VENDOREXPERIMENT=1
    - GOOS=linux
    - GOARCH=amd64
    - CGO_ENABLED=0
  commands:
    - go get github.com/franela/goblin
    - go get ./...
    - go test ./...
    - go build

publish:
  docker:
    username: fracting
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: fracting/drone-exec
    tag: [ "testing", "0.4.2t" ]
    when:
      repo: fracting/drone-exec
      branch: [ "master", "custom-shell-20160623-v1" ]
