
build:
  image: golang:1.5
  environment:
    - GOPATH=/drone
    - GO15VENDOREXPERIMENT=1
    - GOOS=linux
    - GOARCH=amd64
    - CGO_ENABLED=0
  commands:
    - go get github.com/franela/goblin
    - go get ./...
    - go test ./...
    - go build

notify:
  irc:
    prefix: build
    nick: drone-exec
    channel: wine-zh
    server:
      host: chat.freenode.net
      port: 6667

publish:
  docker:
    username: fracting
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: fracting/drone-exec
    tag:
      - "latest"
      - "0.4"
    when:
      repo: fracting/drone-exec
      branch: master

